### ISSUE TITLE
Undefined Symbols Referenced From RKClient

### ISSUE THREAD

**Issue by QuintonC** [samsymons/RedditKit#58]
Undefined symbols for architecture x86_64:
  **"_OBJC_CLASS_$_RKClient", referenced from:**
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
**clang: error: linker command failed with exit code 1 (use -v to see invocation)**

Are the two errors that I'm getting after implementing the RK. Any ideas?

**Comment by samsymons** [comment]
Interesting – are you using CocoaPods or submodules?

**Comment by rickharrison** [comment]
Closing for now. Please post any updated info you have and I will take a look.
