### ISSUE TITLE
"NSString+HTML.h" filename conflicts with DTCoreText

### ISSUE THREAD

**Issue by ThePantsThief** [samsymons/RedditKit#71]
Since it's only used in one file, you could copy the category method into that .m file, or you could rename the category file. Or you could leave it, but I'm probably not the only one who uses DTCoreText with RedditKit to parse markdown into HTML, haha.

The conflict is that importing NSString+HTML.h imports the one in DTCoreText.

**Comment by samsymons** [comment]
Good call – I'll have that fixed by the end of the day.

**Comment by ThePantsThief** [comment]
Thanks man 😁

--
Tanner Bennett
