### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by pavementscratcher** [samsymons/RedditKit#81]
Is RedditKit still being actively maintained? No offense meant by this question, I'm only electing to ask because there hasn't been any updates to either the main or beta branch in months, specifically oAuth is something sorely missing.

Should we migrate to a different solution for the Reddit API and Objective-C?

**Comment by rickharrison** [comment]
Yes it is being maintained. It is a very stable library that is powering successful applications. Yes, it is currently missing oauth, but this is something we would like to add in the near future.
